spin_manifest_version = 2

# General identification information
[application]
name = "$proto_id"
version = "0.2.0"
description = ""

[variables]
redis_host = { required = true }  # will be filled out in ENV
postgres_host = { required = true }  # will be filled out in ENV
proto_id = { required = true }  # will be filled out in ENV
wasm_hash = { required = true }  # will be filled out in ENV

[application.trigger.redis]
address = "redis://{{redis_host}}"

[[trigger.redis]]
channel = "vin2worker"
component = "$proto_id"

[[trigger.redis]]
channel = "vin2worker:$proto_id"
component = "$proto_id"

[component.$proto_id]
description = ""
source = "../wasm_files/$wasm_hash.wasm"
## TODO: replace it in docker compose file
# allowed_outbound_hosts = ["redis://localhost:6379", "postgres://localhost:5432"]
allowed_outbound_hosts = ["redis://{{redis_host}}", "postgres://{{postgres_host}}"]

[component.$proto_id.variables]
redis_host = "{{ redis_host }}"
postgres_host = "{{ postgres_host }}"
proto_id = "{{ proto_id }}"
wasm_hash = "{{ wasm_hash }}"

# How to build the Wasm module from source
[component.$proto_id.build]
command = "cargo build --target wasm32-wasi --release"
